name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [main]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: $/.github/workflows/build.yml
